---
apiVersion: v1
data:
  config.yml: |
    autodiscovery_tag: prometheus_io_azure_exporter_discover
    autodiscovery_mode: All
    update_metrics_functions:
    - name: storage
      interval: 2h
    - name: batch
      interval: 30s
    - name: graph
      interval: 5m
kind: ConfigMap
metadata:
  name: prometheus-azure-exporter-config
  namespace: monitoring
---
apiVersion: v1
data:
  AZURE_TENANT_ID: <uuid>
  AZURE_SUBSCRIPTION_ID: <uuid>
kind: ConfigMap
metadata:
  name: prometheus-azure-exporter-env
  namespace: monitoring
