---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus-azure-exporter
  name: prometheus-azure-exporter
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-azure-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: prometheus-azure-exporter
    spec:
      containers:
      - env:
        - name: AZURE_TENANT_ID
          value: <uuid>
        - name: AZURE_SUBSCRIPTION_ID
          value: <uuid>
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: prometheus-azure-exporter
              key: AZURE_CLIENT_ID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: prometheus-azure-exporter
              key: AZURE_CLIENT_SECRET
        image: quay.io/sylr/prometheus-azure-exporter:master
        imagePullPolicy: Always
        name: prometheus-azure-exporter
        resources:
          requests:
            cpu: 60m
            memory: 64Mi
          limits:
            cpu: 2
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
