---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: prometheus-azure-exporter
  name: prometheus-azure-exporter
  namespace: monitoring
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-azure-exporter
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: prometheus-azure-exporter
    spec:
      containers:
      - args:
        - "--config=/etc/prometheus-azure-exporter/config.yml"
        envFrom:
        - configMapRef:
            name: prometheus-azure-exporter-env
        - secretRef:
            name: prometheus-azure-exporter
        image: quay.io/sylr/prometheus-azure-exporter:master
        imagePullPolicy: Always
        name: prometheus-azure-exporter
        resources:
          requests:
            cpu: 60m
            memory: 64Mi
          limits:
            cpu: 2
            memory: 512Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus-azure-exporter
          name: prometheus-azure-exporter-conf-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: prometheus-azure-exporter-conf
        name: prometheus-azure-exporter-conf-volume
