language: go

dist: trusty

go:
- "1.11.x"

go_import_path: github.com/sylr/prometheus-azure-exporter

env:
- GO111MODULE=on

script:
- gofmt -d -e -l . && git diff --quiet
- go mod tidy -v && git diff --quiet
- go test -v ./...
- go build
