language: go

dist: xenial

go:
- "1.11.x"

go_import_path: github.com/sylr/prometheus-azure-exporter

env:
- GO111MODULE=on

services:
- docker

install:
- true

script:
- gofmt -d -e -l . && git diff --quiet
- go mod tidy -v && git diff
- go mod vendor && git diff --exit-code
- go test -v ./...
- go build -ldflags "-X main.Version=$(git describe --dirty --broken || git rev-parse --short HEAD)"
- docker build .
